# Generated by Django 2.2.7 on 2023-04-12 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.TextField(default=None, null=True)),
                ('objects_detected', models.TextField(default=None, null=True)),
                ('time_stamp', models.DateField(default=None, null=True)),
            ],
        ),
    ]
